name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.8, 3.9, "3.10"]
    services:
      rqlite:
        image: rqlite/rqlite
        options: -p4001:4001
    steps:
      - name: Setup Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}
      - name: Fetch rqlite
        uses: actions/checkout@v2
      - name: Generic python setup
        run: |
          python -m pip install --upgrade pip
      - name: Installing dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Lint rqlite with black
        run: |
          python -m black --check src/rqlite
      - name: Lint tests with black
        run: |
          python -m black --check tests
      - name: Run tests
        working-directory: ./tests
        run: |
          python -m unittest discover -s .
